// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcN5he4zN046-_ukMN9aLzDlJs07gCuaE',
    appId: '1:475084501813:web:8405774d79ba0825a6527c',
    messagingSenderId: '475084501813',
    projectId: 'mr-defence-d9934',
    authDomain: 'mr-defence-d9934.firebaseapp.com',
    storageBucket: 'mr-defence-d9934.firebasestorage.app',
    measurementId: 'G-EDW96QQFCV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBR3-IYxCaSdQwatwlyisMmjC4QS1A7Z9I',
    appId: '1:475084501813:android:e4e837c3f7398802a6527c',
    messagingSenderId: '475084501813',
    projectId: 'mr-defence-d9934',
    storageBucket: 'mr-defence-d9934.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKbybAbmAtxSjDA_Bv4QC8zGJRPAzRgYk',
    appId: '1:475084501813:ios:22c8dbfbda5c1220a6527c',
    messagingSenderId: '475084501813',
    projectId: 'mr-defence-d9934',
    storageBucket: 'mr-defence-d9934.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKbybAbmAtxSjDA_Bv4QC8zGJRPAzRgYk',
    appId: '1:475084501813:ios:22c8dbfbda5c1220a6527c',
    messagingSenderId: '475084501813',
    projectId: 'mr-defence-d9934',
    storageBucket: 'mr-defence-d9934.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcN5he4zN046-_ukMN9aLzDlJs07gCuaE',
    appId: '1:475084501813:web:4a76beebc500691ca6527c',
    messagingSenderId: '475084501813',
    projectId: 'mr-defence-d9934',
    authDomain: 'mr-defence-d9934.firebaseapp.com',
    storageBucket: 'mr-defence-d9934.firebasestorage.app',
    measurementId: 'G-2S2Z01Y5VT',
  );
}
